name: japanesewalking
description: "Japanese Walking timer app with customizable intervals and clear audio cues for optimal walking rhythm."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_background_service: ^5.0.0
  audioplayers: ^6.0.0
  wakelock_plus: ^1.0.0
  permission_handler: ^12.0.0
  in_app_purchase: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_core: '>=2.21.1'
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  intl: 0.20.2
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
